# Generated by Django 2.0.4 on 2018-04-05 09:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyhoso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên lao động')),
                ('year_of_birth', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('id_card_number', models.CharField(max_length=12)),
                ('result', models.PositiveSmallIntegerField(choices=[(0, 'Chưa có'), (1, 'Đạt'), (2, 'Có vấn đề'), (3, 'Loại')], default=0)),
                ('deadline', models.DateField(default=datetime.date(2018, 4, 8))),
                ('is_returned', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Chủ lao động'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'Bệnh viện'},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Liên hệ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên bệnh viện'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanlyhoso.Employer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanlyhoso.Hospital'),
        ),
    ]
