# Generated by Django 2.0.4 on 2018-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyhoso', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
