# Generated by Django 2.0.4 on 2018-04-05 11:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyhoso', '0004_auto_20180405_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Người môi giới'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Người khám'},
        ),
        migrations.AddField(
            model_name='profile',
            name='action_date',
            field=models.DateField(default=datetime.date(2018, 4, 5), verbose_name='Ngày khám'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deadline',
            field=models.DateField(default=datetime.date(2018, 4, 8), verbose_name='Hạn trả kết quả'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanlyhoso.Employer', verbose_name='Người môi giới'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanlyhoso.Hospital', verbose_name='Bệnh viện'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_number',
            field=models.CharField(max_length=12, verbose_name='Số CMND'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Trả kết quả'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Chưa có'), (1, 'Đạt'), (2, 'Có vấn đề'), (3, 'Loại')], default=0, verbose_name='Kết quả'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)], verbose_name='Năm sinh'),
        ),
    ]
